/**
 * Runs the replay harness over a stated universe and writes the results table.
 *
 * This exists because the headline validation number was published with the
 * half that decides it left blank. `GSPS_Replay_Harness_Test_Results_29pct.pdf`
 * reported a 29% win rate and left total trades, expectancy, and every
 * per-bucket cell as "[Enter value]" — while the document's own text says
 * expectancy is the deciding metric. At a 2R target, break-even is a 33.3% win
 * rate; at 3R it is 25%. So the same 29% is a losing system or a winning one
 * depending on a cell that was never filled in.
 *
 * Usage:
 *   npm run backtest                                    # writes docs/REPLAY_RESULTS.md
 *   npm run backtest -- --symbols SPY,AAPL --targetR 3  # a different universe and target
 *   npm run backtest -- --stdout                        # print instead of writing
 *
 * It refuses to write a report from synthetic bars. With no vendor credentials
 * configured, `getMarketDataProvider()` falls back to a seeded random walk that
 * will happily produce a full table of numbers describing nothing — which is
 * precisely the way a placeholder becomes a published finding. Configure
 * `ALPACA_API_KEY` / `ALPACA_API_SECRET` (see `.env.example`) and run it again.
 *
 * TypeScript is loaded through Vite so the `@/` alias and the app's own modules
 * resolve exactly as they do in the app — the report describes the shipped code,
 * not a copy of it.
 */

import { createServer } from "vite";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { writeFile } from "node:fs/promises";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** Where a run lands by default. `--stdout` prints instead of writing. */
const DEFAULT_OUT = "docs/REPLAY_RESULTS.md";

export function parseArgs(argv) {
  const args = {
    symbols: null,
    timeframe: "15Min",
    targetR: 2,
    within: "Execute",
    out: DEFAULT_OUT,
  };
  for (let i = 0; i < argv.length; i++) {
    const [flag, inline] = argv[i].split("=");
    if (flag === "--stdout") {
      args.out = null;
      continue;
    }
    const value = inline ?? argv[++i];
    switch (flag) {
      case "--symbols": args.symbols = value.split(",").map((s) => s.trim().toUpperCase()).filter(Boolean); break;
      case "--timeframe": args.timeframe = value; break;
      case "--targetR": args.targetR = Number(value); break;
      case "--within": args.within = value; break;
      case "--out": args.out = value; break;
      default:
        throw new Error(`Unknown argument '${flag}'. See the header of scripts/replay-report.mjs.`);
    }
  }
  return args;
}

const pct = (n) => `${(n * 100).toFixed(1)}%`;
const r = (n) => `${n >= 0 ? "+" : ""}${n.toFixed(3)}R`;

export function markdown(report, args) {
  const lines = [];
  const day = (t) => (t ? t.slice(0, 10) : "unknown");

  lines.push("# Replay harness results");
  lines.push("");
  lines.push(
    "Generated by `npm run backtest` (scripts/replay-report.mjs). Every number below comes from",
    "`lib/backtest/replay.ts` replaying the shipped entry logic bar by bar. Regenerate rather than",
    "edit: a hand-edited cell here is exactly the failure this file replaces.",
  );
  lines.push("");
  lines.push("## Run");
  lines.push("");
  lines.push("| | |");
  lines.push("|---|---|");
  lines.push(`| Universe | ${report.symbols.join(", ") || "none"} |`);
  lines.push(`| Window | ${day(report.window.from)} → ${day(report.window.to)} |`);
  lines.push(`| Execution timeframe | ${report.timeframe} |`);
  lines.push(`| Target | ${report.targetR}R |`);
  lines.push(`| Break-even win rate at this target | ${pct(report.breakEvenWinRate)} |`);
  lines.push(`| Data source | ${report.source} (${report.live ? "live feed" : "SYNTHETIC"}) |`);
  lines.push(`| Armed / triggered | ${report.armed} / ${report.triggered} |`);
  lines.push(`| Generated | ${report.generatedAt} |`);
  if (report.skipped.length > 0) {
    lines.push(
      `| Skipped | ${report.skipped.map((s) => `${s.symbol} (${s.reason})`).join("; ")} |`,
    );
  }
  lines.push("");

  lines.push("## Expectancy by verdict");
  lines.push("");
  lines.push(
    "Expectancy is the deciding metric, not win rate. A win rate below the break-even figure above",
    "is a losing system at this target however good it looks.",
  );
  lines.push("");
  lines.push("| Bucket | Trades | Win rate | Expectancy | Total | Above break-even |");
  lines.push("|---|---:|---:|---:|---:|---|");
  for (const b of report.buckets) {
    lines.push(
      `| ${b.bucket} | ${b.trades} | ${b.trades === 0 ? "—" : pct(b.winRate)} | ${
        b.trades === 0 ? "—" : r(b.expectancyR)
      } | ${b.trades === 0 ? "—" : r(b.totalR)} | ${b.trades === 0 ? "—" : b.profitable ? "yes" : "no"} |`,
    );
  }
  const o = report.overall;
  lines.push(
    `| **All** | ${o.trades} | ${o.trades === 0 ? "—" : pct(o.winRate)} | ${
      o.trades === 0 ? "—" : r(o.expectancyR)
    } | ${o.trades === 0 ? "—" : r(o.totalR)} | ${o.trades === 0 ? "—" : o.profitable ? "yes" : "no"} |`,
  );
  lines.push("");

  lines.push(`## Factors inside ${report.attributeWithin}`);
  lines.push("");
  lines.push(
    "Expectancy when each criterion passed versus when it failed. Δ is the lever a weight would be",
    "set from. Marginal, not causal — see docs/BACKTESTING.md.",
  );
  lines.push("");
  lines.push("| Criterion | Passed | E[R] pass | E[R] fail | Δ E[R] | Corr | Verdict |");
  lines.push("|---|---:|---:|---:|---:|---:|---|");
  for (const f of report.factors) {
    lines.push(
      `| ${f.criterion} | ${f.passed.n}/${f.observed} | ${
        f.passed.n === 0 ? "—" : r(f.passed.expectancyR)
      } | ${f.failed.n === 0 ? "—" : r(f.failed.expectancyR)} | ${
        f.deltaExpectancyR === undefined ? "—" : r(f.deltaExpectancyR)
      } | ${f.correlation === undefined ? "—" : f.correlation.toFixed(2)} | ${f.verdict} |`,
    );
  }
  lines.push("");

  lines.push(`## Stop width inside ${report.attributeWithin}`);
  lines.push("");
  lines.push("| Band (×ATR) | Trades | Win rate | Expectancy |");
  lines.push("|---|---:|---:|---:|");
  for (const b of report.atrBands) {
    lines.push(
      `| ${b.from.toFixed(1)}–${b.to === null ? "∞" : b.to.toFixed(1)} | ${b.trades} | ${
        b.trades === 0 ? "—" : pct(b.winRate)
      } | ${b.trades === 0 ? "—" : r(b.expectancyR)} |`,
    );
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    `Reproduce: \`npm run backtest -- --symbols ${report.symbols.join(",")} --timeframe ${
      report.timeframe
    } --targetR ${report.targetR} --within ${args.within}\``,
  );
  lines.push("");
  lines.push(
    "The harness is deliberately pessimistic — a setup may only trigger on the very next bar, a bar",
    "covering both stop and target counts as a loss, and round-trip friction is charged against every",
    "trade. It still cannot see the intra-bar path or the real bid/ask at the fill. Treat any result",
    "as an upper bound.",
  );
  lines.push("");

  return lines.join("\n");
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  const server = await createServer({
    configFile: false,
    root,
    resolve: { alias: { "@": root } },
    server: { middlewareMode: true },
    appType: "custom",
    logLevel: "warn",
  });

  try {
    const { runBacktest } = await server.ssrLoadModule("/lib/backtest/run.ts");

    const symbols = args.symbols ?? ["SPY", "AAPL", "AMD", "TSLA", "MSFT", "NVDA"];
    process.stderr.write(`Replaying ${symbols.join(", ")} on ${args.timeframe} at ${args.targetR}R…\n`);

    const report = await runBacktest({
      symbols,
      timeframe: args.timeframe,
      targetR: args.targetR,
      attributeWithin: args.within,
    });

    if (!report.live) {
      process.stderr.write(
        `\nRefusing to write a report: bars came from the '${report.source}' generator, which is a\n` +
          `seeded random walk. Configure ALPACA_API_KEY and ALPACA_API_SECRET (see .env.example) and\n` +
          `run this again. Nothing was written.\n`,
      );
      process.exitCode = 1;
      return;
    }

    if (report.overall.trades === 0) {
      process.stderr.write(
        `\nRefusing to write a report: the run produced no trades. ${report.armed} setups armed and ` +
          `${report.triggered} triggered. Widen the universe or check the data window.\n`,
      );
      process.exitCode = 1;
      return;
    }

    const out = markdown(report, args);
    if (args.out) {
      await writeFile(path.resolve(root, args.out), out, "utf8");
      process.stderr.write(`\nWrote ${args.out}\n`);
    } else {
      process.stdout.write(out);
    }
  } finally {
    await server.close();
  }
}

// Only when run as a command. `markdown` and `parseArgs` are exported so the
// rendering can be exercised without a market-data feed, and importing them must
// not kick off a replay.
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    process.stderr.write(`${err instanceof Error ? err.stack : String(err)}\n`);
    process.exitCode = 1;
  });
}
