-- Restores EXECUTE on resolve_username_email() to anon/authenticated, which
-- a later out-of-band change on the live project ("lock_down_
-- resolve_username_email", applied directly, not through this migrations
-- folder) had revoked.
--
-- Why this is the right call and not just reverting a deliberate lockdown
-- -------------------------------------------------------------------------
-- Supabase's security advisor flags every SECURITY DEFINER function callable
-- by `anon` as a generic warning (see the other functions locked down in
-- 0025_lock_down_analytics_rpcs.sql). resolve_username_email is a different
-- shape of function from those: it takes no user id and returns nothing
-- attacker-chosen — a username in, the one matching email out, nothing else
-- — the same exposure as any "forgot password" lookup. It exists
-- specifically to be called by a session that isn't authenticated yet
-- (0020_username_login.sql): resolving a username to an email is the first
-- step of username-based login, before any Supabase Auth call can happen.
-- Revoking `anon`'s execute grant doesn't harden it, it silently breaks
-- username login for every account on the platform — discovered here
-- because it broke sign-in for the showcase demo profile
-- (0028_demo_showcase_profile.sql), which uses a username rather than
-- its email.
--
-- Rollback
-- --------
-- `revoke execute on function public.resolve_username_email (text) from anon, authenticated;`
-- Reintroduces the same breakage this migration fixes — only do this if
-- username login is being deliberately removed as a feature.

grant execute on function public.resolve_username_email (text) to anon, authenticated;
